name: .NET

on:
  push:
    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
       find: "#{{jwtSecret}}"
       replace: "ajrho487ry34o9tcw13sda"
       include: "appsettings.json"
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
